### ISSUE TITLE
Beta?

### ISSUE THREAD

**Issue by justinmchase** [WalkerCodeRanger/semver#83]
The 3.0 beta version has been out there for a while, just wondering when an official 3.0 may be planned for?

**Comment by WalkerCodeRanger** [comment]
I've been busy with work and other projects, but you're right it has been a long time and most/all the changes for 3.0 seem to be done. I'll try to get 3.0 out on or before 2024-09-30. I've updated the milestone due date to reflect that.

**Comment by WalkerCodeRanger** [comment]
I've published v3.0.0-beta.2, which I expect will be identical to what gets published as v3.0.0 soon.

The primary change that carries any risk is a downgrade of the minimum version of the `Microsoft.Extensions.Primitives` package to avoid conflicts in older codebases.

If you, or anyone else, would like to try out the new beta, it would be appreciated.

**Comment by WalkerCodeRanger** [comment]
v3.0.0 has been released.
* [Release Notes](https://github.com/WalkerCodeRanger/semver/releases/tag/v3.0.0)
* [NuGet](https://www.nuget.org/packages/Semver/3.0.0)
